### PR TITLE
Document Slot fix

### PR DESCRIPTION
**Pull request by benoitgrelard**
https://github.com/radix-ui/primitives/pull/1376

### CODE REVIEW

**Comment by andy-hook** [comment]
Should we bump the page version number for completeness?

**Comment by benoitgrelard** [comment]
Arr, yes I always forget.

**Comment by benoitgrelard** [comment]
Updated all based on latest info here: https://github.com/radix-ui/primitives/commit/f2d50b0d310fbe2168333ceff95c7f43133fe7f0

**Review by andy-hook — APPROVED** [review]
Ohh nice one, I was only thinking about the slot page at the time 😄

**Pull request merged**
