### PR TITLE
[Tooltip] fix wrong anatomy

### PR DESCRIPTION
**Pull request by benoitgrelard**
Raised here: https://github.com/radix-ui/primitives/issues/590#issuecomment-817177537

### CODE REVIEW

**Comment by pacocoursey** [comment]
Thank you! Not sure if should be a separate PR, but I noticed something similar for the Slider component:

```js
  <Slider.Root>
    <Slider.Track>
      <Slider.Thumb />
    </Slider.Track>
    <Slider.Range />
  </Slider.Root>
```

The Range should be inside Track, and Thumb should be outside:

```diff
  <Slider.Root>
    <Slider.Track>
+      <Slider.Range />
    </Slider.Track>
+    <Slider.Thumb />
  </Slider.Root>
```

**Comment by benoitgrelard** [comment]
Ha, thanks for that @pacocoursey, I'll open another PR.

**Comment by benoitgrelard** [comment]
@peduarte I'll let you merge this or apply these changes on top of yours as you wish.

**Comment by peduarte** [comment]
Done in https://github.com/radix-ui/website/pull/132/commits/bf1ff6ba0e55ad4fb176a20e2d8140ad558c1204

**Pull request closed without merging**
