### PR TITLE
Tweaking styles for new code block

### PR DESCRIPTION
**Pull request by colmtuite**
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code.
- [ ] Include the URL where we can test the change in the body of your PR.

This pull request:

- [ ] Fixes a bug
- [ ] Adds additional features/functionality
- [ ] Updates documentation or example code
- [ ] Other

### CODE REVIEW

**Comment by benoitgrelard** [comment]
Merging this in.

**Comment by andy-hook** [comment]
Would `ScrollArea` be contender for handling the overflow? the current gradient overlay on the scrollbar interferes with the interaction and doesn't look great.

**Comment by benoitgrelard** [comment]
> Would ScrollArea be a contender for handling the overflow?

Yep, I will look at this. 

> the current gradient overlay on the scrollbar interferes with the interaction and doesn't look great.

I agree, I raised to Colm but he ran out of time. I'll ask Vlad if he has some time.

**Comment by andy-hook** [comment]
> I'll ask Vlad if he has some time.

I think the gradient is good as an overflow affordance (it just looks a bit odd on top of the native bar) if we can slot a custom bar over the top that'd probably be enough. Happy to help if needed.

**Comment by benoitgrelard** [comment]
What do you call "the native bar" here?

**Comment by andy-hook** [comment]
CleanShot 2022-11-04 at 10 28 14

**Comment by benoitgrelard** [comment]
ah yeah ok, I've added a check in the list to add scroll area.
My main issue with the current collapse/expand UI is that it's not very accessible, can't really see the button, it's muddy on top of the text behind, etc.

**Pull request merged**
