### PR TITLE
Edit invalid accessibility patterns urls

### LINKED ISSUE #403: Revise WAI-ARIA practices urls
Recently https://www.w3.org/TR/wai-aria-practices-1.2 was updated with a note that the information had been moved, the intention now seems to be for them to provide an evergreen resource via https://www.w3.org/WAI/ARIA/apg/

> This version of WAI-ARIA Authoring Practices is published to retire it from the Working Group Note track. The content continues to be updated in a format that is more useful to developers: https://www.w3.org/WAI/ARIA/apg/

> The content continues to evolve in that location. The content is no longer versioned, but continuously updated. Improved code examples are also part of that resource

Honestly I think the communication around this is a bit confusing, It’s not clear when to reference [the editors draft](https://w3c.github.io/aria-practices/) over that new AGP resource.

So I’m opening this issue to prompt the conversation. It doesn’t look like there are any plans by the WG to provide redirects so we need to update our URLs one way or the other.

### PR DESCRIPTION
**Pull request by hugodessomme**
Several urls about accessibility patterns were invalid in the documentation. I replaced these urls with the good ones!

This pull request:

- [ ] Fixes a bug
- [ ] Adds additional features/functionality
- [x] Updates documentation or example code
- [ ] Other

Closes #403

### CODE REVIEW

**Comment by benoitgrelard** [comment]
Hi @hugodessomme, we have a related open issue here: #403.
We need to update this globally for all primitives, as well as all the previous version files (not just the latest ones).
Would you like to continue with that task?

**Comment by hugodessomme** [comment]
Hello @benoitgrelard, I'm ok to continue this task :) By "all primitives", which section of the docs are you refering to?

**Comment by benoitgrelard** [comment]
> By "all primitives", which section of the docs are you refering to?

I just mean any of the mdx files that have a `aria` link in the front matter.

**Comment by benoitgrelard** [comment]
Superseded by #479

**Pull request closed without merging**
