### PR TITLE
Fix: Update ARIA Links globally

### PR DESCRIPTION
**Pull request by donsn**
Updated and tested all ARIA Links

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code.
- [ ] Include the URL where we can test the change in the body of your PR.

This pull request:

- [ ] Fixes a bug
- [ ] Adds additional features/functionality
- [x] Updates documentation or example code
- [ ] Other

### CODE REVIEW

**Comment by donsn** [comment]
Hi @benoitgrelard 
Based on your feedback on [#477 ](https://github.com/radix-ui/website/pull/477#issuecomment-1261477284), I have updated the ARIA Urls globally

There's been no response on [#459](https://github.com/radix-ui/website/pull/459#issuecomment-1223762466) for over a month now

**Review by benoitgrelard — COMMENTED** [review]
Thanks for this @donsn!
After testing the preview, it looks a couple are missing:

- progress should link to: https://www.w3.org/WAI/ARIA/apg/patterns/meter/
- switch should link to: https://www.w3.org/WAI/ARIA/apg/patterns/switch/

All good otherwise!
I'll close the older PR in favour of yours 👍

**Comment by donsn** [comment]
> Thanks for this @donsn! After testing the preview, it looks a couple are missing:
> 
> * progress should link to: [w3.org/WAI/ARIA/apg/patterns/meter](https://www.w3.org/WAI/ARIA/apg/patterns/meter/)
> * switch should link to: [w3.org/WAI/ARIA/apg/patterns/switch](https://www.w3.org/WAI/ARIA/apg/patterns/switch/)
> 
> All good otherwise! I'll close the older PR in favour of yours 👍

Updated

**Review by benoitgrelard — APPROVED** [review]
Amazing ♥️

**Pull request merged**
